@startuml quan_ly_xe
skinparam groupInheritance 3

package TransportationFactory <<Folder>>{

    class Transportation{
        # int: Capacity
        # int: Size
        # string: TypeOfFuel
        # VehicleStatus: Status
        # string: License
        # string: Brand
        + WarrantyService: Warranty
        + Journey: JourneyInCharge
        + DisplayInfo()
    }

    class Container{  
    }

    class Car{
    }

    class Truck{
    }

    class Coach {
    }
}

class WarrantyService{
    - bool: IsWarranty
    - DateTime: WarrantyTime
    - DateTime[]: WarrantyHis
    + DisplayInfo()
    + DisplayWarrantyHistory()
}


enum VehicleStatus{
    1: Active
    2: UnderMaintainace
    3: NotActive
}
class Driver{
    - string: Name
    - string: PhoneNumber
    - string: Address
    - string: Account
    - string: Password
    + Quality: DrivingExperience
    + Journey: JourneyInCharge
    + Journey: JourneyList
    + DisplayInfo()
    + CompleteJourney() 
}

class Journey{
    - Transportation: Vehicle
    - Driver: DriverInCharge
    - double: Kilomet
    - double: Price
    - string: StartLocation
    - string: EndLocation
    - int: Status
    - string: Time
    + DisplayInfo()
}

note top of Journey
Status:
0: chưa đủ điều kiện khởi hành, 1 là đủ, 2 là đã hoàn thành
end note

class Admin <<Singleton>>{
    - string: Account
    - string: Password
    --
    + AddNewVehicle()
    + AddNewDriver()
    + DisplayVehicle()
    + DisplayDrive()
    + AddJourney()
    - CalPrice()
    + CheckForWarranty()
    + CheckIncome()
}

enum Quality{
    1, 2, 3
}

note bottom of Quality
1 (tương đương bằng B) lái đc car 
2 (tương đương bằng C) lái đc truck, (và car)
3 (tương đương bằng D) lái đc coach (và car, truck)
end note

Transportation <|-- Truck
Transportation <|-- Car
Transportation <|-- Coach
Transportation <|-- Container
Transportation -right- WarrantyService
Driver -right- Quality
Driver "1"-down-* "0..*"Journey
VehicleStatus -up- Transportation
Admin -down[dashed]-> Transportation: Adds & Updates & Assign for Journey
Admin -left[dashed]-> Driver: Adds & Journey assignment & Observe
Journey <-right[dashed]- Admin: Create & Observe
Transportation -left-*Journey
@enduml